hosts:
  production:
    hostname: 78.47.62.21
    remote_user: transj
    port: 222
    labels:
      stage: production
    deploy_path: '~/public_html/wp-content/themes'
    branch: master
  stage:
    hostname: stage.xinc.digital
    remote_user: stage
    labels:
      stage: stage
    deploy_path: '~/web/groups.stage.xinc.digital/public_html/wp-content/themes'
